### PR TITLE
Gradle Upgrade

### PR DESCRIPTION
**Pull request by NalediMadlopha**
- Add myself as a contributor to the project
- Bump-up Gradle distributions version
- Gradle Update
     * Bump-up the compile and target SDK versions
     * Remove the recycler view's explicit dependency implementation, the
        recycler view is included in the Android Support AppCompat
     * Add the Android Support Design library
     * Implement Glide as a dependency, Glide will be used to render and
       cache images from the API
- Gradle Tools Upgrade
     * Bump-up the Kotlin version
     * Bump-up the Gradle build tools

### CODE REVIEW

**Review by wzieba — APPROVED** [review]

**Comment by NalediMadlopha** [comment]
@nikhilbansal97 and @ppiliar how are you guys storing the API key? I can't seem to get my build to pass. I am not familiar with Travis CI.

**Comment by ppiliar** [comment]
Api key can be set as environment variable in project settings at https://travis-ci.org/. This can be then accessed with System.getenv(variableName). The thing is, this would not work on your development computer. I will make PR so that travis will load Api key directly to gradle.properties. This way it will work both on travis and development pc without change in build.gradle.

**Comment by NalediMadlopha** [comment]
Okay cool, I'll have to remove the usage of `System.env(...)` then hopefully my PR will pass once yours has passed.

**Comment by NalediMadlopha** [comment]
@nikhilbansal97 my build finally succeeded, if you are happy please merge.

**Comment by nikhilbansal97** [comment]
> @nikhilbansal97 my build finally succeeded, if you are happy please merge.

@NalediMadlopha 😂 Done Sir!

**Pull request merged**
